### ISSUE TITLE
Facing an issue while retriving a list that has more than 100000 results.

### ISSUE THREAD

**Issue by monk4june** [demgenman/paRdot#12]
We use Pardot for email campaign management in our organization. I am using your library as it was mentioned under supported API wrappers for Pardot API, for an internal analytics implementation. I am trying to retrieve a list using its list id. It worked fine till the number of records in the list were under 100000. As soon as the number surpassed 100000, the client could not fetch records only up to 100000 records and following warning was logged in console. 

Can you please take a look and suggest any other approach or make a fix if possible. 

```
Warning message:
In pardot_client.get_data_frame(iterative_request_url) :
  Invalid value specified for offset
```

**Comment by demgenman** [comment]
Pardot seems to limit the number of results it returns to 100k results at a time for a single type of API call. To retrieve more result use query search criteria parameters like created_after, created_before, id_greater_than and id_less_than in subsequent function calls.
