### ISSUE TITLE
Failure on Install

### ISSUE THREAD

**Issue by bdJohnson72** [demgenman/paRdot#13]
Not an R  dev at all. But hoping I can make use of this package. I am getting a failure on install and was hoping you might have a suggestion. 

Error: package or namespace load failed for 'paRdot' in namespaceExport(ns, exports):
 undefined exports: set_curl_options
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/Admin/Documents/R/win-library/3.5/paRdot'
* restoring previous 'C:/Users/Admin/Documents/R/win-library/3.5/paRdot'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/Admin/AppData/Local/Temp/RtmpicNO8L/file3c80a2b6864/paRdot_0.4.0.tar.gz’ had non-zero exit status

**Comment by demgenman** [comment]
Looks like a file is missing in the package pushed to github. Rebuilt and pushed. Should be fine now.
