### ISSUE TITLE
Trying to install paRdot package in R version 3.5.0 . I have tried creating a new library as well.I get the error as below.I am on Windows 10 . 64 bit. Never saw this error before while installing any other package

### ISSUE THREAD

**Issue by kanny789** [demgenman/paRdot#14]
> devtools::install_github("demgenman/paRdot")
Downloading GitHub repo demgenman/paRdot@master
from URL https://api.github.com/repos/demgenman/paRdot/zipball/master
Installing paRdot
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/karan/AppData/Local/Temp/RtmpA7eMiW/devtools1e8419e4f9f/demgenman-paRdot-db77cca"  \
  --library="C:/Users/karan/Documents/R/win-library/3.5"  \
  --install-tests 

* installing *source* package 'paRdot' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'paRdot'
    finding HTML links ... done
    pardot_account                          html  
    pardot_campaigns                        html  
    pardot_client                           html  
    pardot_email                            html  
    pardot_email_clicks                     html  
    pardot_email_stats                      html  
    pardot_email_template                   html  
    pardot_forms                            html  
    pardot_lifecycle_histories              html  
    pardot_lifecycle_stages                 html  
    pardot_list_memberships                 html  
    pardot_lists                            html  
    pardot_prospect_accounts                html  
    pardot_prospects                        html  
    pardot_tag_objects                      html  
    pardot_tags                             html  
    pardot_users                            html  
    pardot_visitor_activities               html  
    pardot_visitors                         html  
    pardot_visits                           html  
    set_credentials                         html  
    set_curl_options                        html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'paRdot' in namespaceExport(ns, exports):
 undefined exports: set_curl_options
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'paRdot' in namespaceExport(ns, exports):
 undefined exports: set_curl_options
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Users/karan/Documents/R/win-library/3.5/paRdot'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by demgenman** [comment]
Looks like a file is missing in the package I pushed to github. Rebuilt and pushed. Should be fine now.

**Comment by kanny789** [comment]
Thank you :+1:
